### ISSUE TITLE
Drilldown on chart - no Queries returned

### ISSUE THREAD

**Issue by SQLGeordie** [spaghettidba/WorkloadTools#100]
I have been running some random workload tests on my local machine to get more comfortable with the tool before using it as part of a project. Whilst viewing the output in WorkloadViewer and drilling down on the chart (middle click mouse and highlight intervals) where the benchmark is still running after the baseline had finished, I got no results when I went into Queries. 

My tests were running random workload against (baseline) WideWorldImporters on SQL 2019 (12vCPU and max mem set to 20GB ram) and replaying on the same instance but I changed SQL Server to (benchmark) have only 1 cpu in processor affinity and max mem set to 4GB. 

**NOTE: This was just a test to see differences on a local instance, not a server I am trying to migrate to**

Screenshots and Analysis database backup files attached. Schemas used in the report are baseline and replaytargetbenchmark1cpu.

[ScreenShotsAndAnalysisDBbackup.zip](https://github.com/spaghettidba/WorkloadTools/files/5541342/ScreenShotsAndAnalysisDBbackup.zip)
![WLT-2](https://user-images.githubusercontent.com/15836050/99155161-6162e180-26ad-11eb-978d-4fd49d012256.png)
![WLT-1](https://user-images.githubusercontent.com/15836050/99155163-61fb7800-26ad-11eb-8344-377e5df4dd34.png)

**Comment by spaghettidba** [comment]
Thanks for reporting the issue. Unfortunately I'm joining the dat in memory using LINQ and there is no FULL JOIN readily available. I tried a couple of solutions but I'm not satisfied with the performance. I'm still working on it, I'll keep you posted.

**Comment by spaghettidba** [comment]
Should be ok now. Can I close this one @SQLGeordie?

**Comment by SQLGeordie** [comment]
If you're happy, then I'm happy big man 👌
