### ISSUE TITLE
Make it compatible with Azure SQLDB

### ISSUE THREAD

**Issue by spaghettidba** [spaghettidba/WorkloadTools#11]
Trace and XE streaming API are not available, so it should use something else

**Comment by spaghettidba** [comment]
Closed by polling XE file target on blob storage

**Comment by samplesty** [comment]
Would it be possible to get a template in WorkloadTools/Config for how to structure these connections for Azure? I'm having trouble getting basic connections established. I'm simply trying to setup an ExtendedEventsWorkloadListener and a ReplayConsumer. I have all the xEvents framework setup and files ready to go.

Thanks!
