### ISSUE TITLE
ViewerWorkload Error

### ISSUE THREAD

**Issue by hajerty** [spaghettidba/WorkloadTools#114]
Hi, I took 2 workload and put them in a SqlWorkload db with 2 differents schema.
When I'm opening the viewer I can confirm the connection but I don't find any data. In the error log I find more times this error.

Could you help me please? 

Thanks

2022-01-14 15:21:30.4684 - Skipping invalid datapoint at 6 because of Exception:    in System.Data.SqlClient.SqlBuffer.get_Int64()
   in WorkloadViewer.Model.WorkloadAnalysis.Load() in C:\GitHub\WorkloadTools\WorkloadViewer\Model\WorkloadAnalysis.cs:riga 89

**Comment by spaghettidba** [comment]
It looks like something went wrong when reading the data from the workload database. One (or all) the rows have the column "avg_cpu_us" with invalid data (NULL or something that doesn't fit in a int64).
Have a look at the data
