### ISSUE TITLE
WorkloadViewer shows queries twice, with inverted stats (baseline <--> benchmark)

### ISSUE THREAD

**Issue by CrazySwimmer** [spaghettidba/WorkloadTools#115]
It is the exact same workload captured in two different ways.
Baseline was captured from `ExtendedEventsWorkloadListener` to `AnalysisConsumer` + `WorkloadFileWriterConsumer`
Benchmark was captured from `FileWorkloadListener` to `AnalysisConsumer`
The benchmark does not come from a replay.

The query marked in red appears only once because I stopped the benchmark analysis before it was finished.

![image](https://user-images.githubusercontent.com/32016866/155890068-2e5b5d56-67fa-469e-a116-1ecddaf32fa7.png)

**Comment by CrazySwimmer** [comment]
I can confirm that I get the same result even after full replays, no matter what two workloads I compare.

An interesting point I noticed is that I can select either of any two queries and the "Query Details" pane will always show only one result (i.e., not inverted).
I would guess this points to a problem in how the merge is done in the "Queries" pane.

**Comment by CrazySwimmer** [comment]
Hi Gianluca,
Apologies for the late reply.
Where should I upload the analysis database?

**Comment by spaghettidba** [comment]
Wherever you prefer (google drive, onedrive...). If the database is small enough you can attach it to the issue by drag/drop on the comment.

**Comment by CrazySwimmer** [comment]
I took the liberty to anonymize databases, hosts and logins as well.
One precision: this isn't the database from the screenshot above, but the "feature" of interest is still present.

Here's a ZIP containing the backup file:
[WorkloadAnalysis_CrazySwimmer.zip](https://github.com/spaghettidba/WorkloadTools/files/8351996/WorkloadAnalysis_CrazySwimmer.zip)
