### ISSUE TITLE
FileWorkloadListener

### ISSUE THREAD

**Issue by JakubKad** [spaghettidba/WorkloadTools#125]
Hello,

I have a problem with this Listener. Log says that it captured x events but the SQLite file will half that amount when I want to do replay. If I do replay, I get tons of errors regarding Inserts/Updated/Deletes. I think the file might be a problem. Listener is connected to AoAG cluster with routs selects and ReadOnly secundary replica, there might be a problem with this. We have used DatabaseFilter property too. Images included.
![Snímek obrazovky 2022-11-29 114550](https://user-images.githubusercontent.com/119412222/204510513-2221d0b1-d985-4e52-b795-728264decd5d.png)
![image](https://user-images.githubusercontent.com/119412222/204510902-64fca3f7-1c1b-484c-a724-c785595cd28a.png)

**Comment by spaghettidba** [comment]
Hey! Thanks for reporting this.
Replay will not work against a readonly replica, of course, so I guess you have your answer there.
Regarding the count of events, not all recorded events can be replayed. WorkloadTools captures both started and completed events, but saves only started events. This could explain why you get double the count in the messages. I should check and maybe makes this more explicit

**Comment by JakubKad** [comment]
Well, I might express myself badly. I captured the Workload from AoAG cluster and replayed it on local DB, for sake of performance testing. So, I am not sure if the tool captures the whole work on this kind of server.

**Comment by spaghettidba** [comment]
I see. No, I'm not aware of any problem with capturing on an AG replica. All modifications to the local database should start from an identical copy of the source database. We had some slight synchronization issues between sessions that should be fixed in the latest version, even if not currently released. If you build from source (or I release a new version) you might get better results.

**Comment by JakubKad** [comment]
Okay, thanks for your time.
