### ISSUE TITLE
WorkloadViewer: Unable to load data object reference not set to an instance of an object

### ISSUE THREAD

**Issue by mozartapang** [spaghettidba/WorkloadTools#128]
when connecting to a sql server

**Comment by spaghettidba** [comment]
Can you please provide more information?
Some logs will probably help. If possible, please include your JSON config files

**Comment by mozartapang** [comment]
Hi, This is the error when loading Workloadviewer.
I'm loading via command prompt
workloadviewer -S servername\instancename -D WorkloadTools -M sch -U username -P "passwordhere"

[](url)
![Screenshot_2](https://user-images.githubusercontent.com/118723019/226287977-f9f16650-6131-41d9-89c8-677b19243887.jpg)

**Comment by spaghettidba** [comment]
I am unable to reproduce. Does it work if you don't provide command line options and enter the parameters from the GUI?

**Comment by mozartapang** [comment]
yes, same error from GUI

**Comment by spaghettidba** [comment]
Good, thanks for the feedback
