### ISSUE TITLE
Replay on AzureDB hangs

### ISSUE THREAD

**Issue by marceloadade** [spaghettidba/WorkloadTools#154]
Thank you for writing this tool and making it available to us.
I have been able to Replay workloads with no issues on on Prem Instances and on VMs in Azure.

When I try to replay the workloads in an Azure DB, I get connected with no issues and some commands get executed.
However, it reaches a point where the Replay consumer simply hangs and stops producing outputs.
In one execution I left it executing for more than 12 hours with no success. 
When executing against an exact copy of the Database but on premisses, it completes in less than 5 minutes.

Any suggestions, ways to log in which command the tool is at, parameters that could be changed?

![image](https://github.com/spaghettidba/WorkloadTools/assets/17789164/35da971a-2d75-44d5-9a73-309545c8ee36)

A few examples are in the images below.

Thank you again.

![image](https://github.com/spaghettidba/WorkloadTools/assets/17789164/ffaa0217-5b0d-4256-a755-c9d2a8e02804)

![image](https://github.com/spaghettidba/WorkloadTools/assets/17789164/d9472fde-9cd4-4151-a745-2a8109d2c4e6)

**Comment by spaghettidba** [comment]
Hi Marcelo. Do you have any logs you can share with me? You can also email the logs to me if you don't want to upload them here publicly.

**Comment by marceloadade** [comment]
Hi Gianluca, adding more details to this issue:
In all executions of the Replay I did have the same XEvents running.
After all of them, I created SQLITE files for further analysis.

It looks like all commands are executed about twice in Azure, compared to the source events files (which is an Azure SQL DB BTW), the number of events is the same when executing in a local Instance (no issues).

Executing the following query in SQLITE:
```
select sql_text,count (*) from events 
where sql_text not like 'exec sp_reset_connection%'
group by sql_text
order by 2 desc;
```

**Replay execution in Azure:**
![image](https://github.com/spaghettidba/WorkloadTools/assets/17789164/a9b3d1ff-39d5-4842-a0c8-7994047fe13e)


**Replay execution Local:**
![image](https://github.com/spaghettidba/WorkloadTools/assets/17789164/fac3cbb1-2d71-4319-90f6-dae57096ecdb)


**Source:**
![image](https://github.com/spaghettidba/WorkloadTools/assets/17789164/9cc1ca9d-9148-4002-a6df-a80bc9eff734)

**Comment by marceloadade** [comment]
Closing as issue is not happening anymore.
