### ISSUE TITLE
Unable to write workload analysis.

### ISSUE THREAD

**Issue by talenyc** [spaghettidba/WorkloadTools#16]
I am getting following errors on trace replay:

Info - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : 0 rows aggregated
Info - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : 0 rows written
Warn - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : Unable to write workload analysis.
Warn - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : Value cannot be null.
Info - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : 0 rows aggregated
Info - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : 0 rows written
Warn - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : Unable to write workload analysis.
Warn - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : Value cannot be null.
Error - WorkloadTools.Consumer.Analysis.WorkloadAnalyzer : Unable to write workload analysis info to the destination database.

**Comment by spaghettidba** [comment]
Probably it was an empty data table. I added a check in commit 0a3823a1263469a25167de33a77e6093cfb80580

**Comment by talenyc** [comment]
I verified that this issue is fixed in  v1.0.3  97af874 "To null or not to null"
