### ISSUE TITLE
Implement reading workload from existing .trc files

### ISSUE THREAD

**Issue by spaghettidba** [spaghettidba/WorkloadTools#4]

**Comment by tbensonwest** [comment]
+1 for this. Are you actively working on these issues atm? We would be very interested in using this tooling over DEA, but we need to decouple the collection from the replay.

**Comment by spaghettidba** [comment]
I am working on it when time allows. If there's something in particular that you need, please let me know.

**Comment by spaghettidba** [comment]
Reading .trc files directly is not a good idea, because the trace DLLs from Microsoft only work with x86, so they cannot be loaded into a x64 process. The preferred way would be to preprocess the trace files using a converter application written for x86 that converts the .trc files to a sqilte database. See #21

**Comment by spaghettidba** [comment]
This is covered by ConvertWorkload: it converts a trace file to a sqlite database that can be used as the source to SqlWorkload
