### ISSUE TITLE
Error: Arithmetic overflow error converting expression to data type int

### ISSUE THREAD

**Issue by goodsoul1914** [spaghettidba/WorkloadTools#40]
seeing a lot of this type or entries in Warnings.log:
Worker [325] - Error: Arithmetic overflow error converting expression to data type int.
source SQL server 2016
analysis\replay: SQL server 2017

**Comment by goodsoul1914** [comment]
looks like the log collecting all king of warnings\errors from replay server, I will figure the reason

**Comment by spaghettidba** [comment]
Warnings.log contains all the errors captured during the replay, so this is an error occurring on the target SQL Server instance. You should also find the offending statement in the log
