### ISSUE TITLE
on windows server 2016 WorkloadViewer needs to be loaded multiple time

### ISSUE THREAD

**Issue by goodsoul1914** [spaghettidba/WorkloadTools#42]
on windows server 2016 WorkloadViewer needs to be loaded multiple time
the impression is that everytime I open it- it load only one interval of time when data was captured(60sec by default). Issue doesnt exist in windows 2012

**Comment by spaghettidba** [comment]
Can you share the json config file and the log file please?

**Comment by spaghettidba** [comment]
Not enough information
