### ISSUE TITLE
01/01/0001 00:00:00 oldest command date

### ISSUE THREAD

**Issue by ghotz** [spaghettidba/WorkloadTools#49]
During the replay sometimes an error similar to the following is logged:

> 2019-04-12 01:33:14.4887 - Info - WorkloadTools.Consumer.Replay.ReplayConsumer : 01/01/0001 00:00:00 oldest command date

The error is risen periodically and after a while the tool completely stops replaying and just logs this error (as if there's nothing to replay). 

More info:
1. 16 CPUs on the replaying server all at 100% usage
2. 500 workers configured in Workloadtools, around 300 used
3. many errors during replay (e.g. trying inserting NULLs, missing procedures)

**Comment by spaghettidba** [comment]
Seems like the target server can't keep up with the workload. Have you tried capturing sp_whoIsActive to see whether some queries are being replayed and got stuck?

**Comment by ghotz** [comment]
Yes, queries are regularly stuck waiting for CPUs or PFSs on tempdb, but is expected since the destination system run constantly at 100% with 8 cores (the original workload has 32 cores). Still, the message should output a proper date and the real problem is that it stops sending commands to the Replay Consumer even tough it's collecting them and writing them to the Analysis Consumer.
