### ISSUE TITLE
Error while replaying "blob" events

### ISSUE THREAD

**Issue by spaghettidba** [spaghettidba/WorkloadTools#54]
When replaying events from a sqlite database, timeout events are not interpreted correctly, because they're lacking some information (reads and writes for instance).

**Comment by spaghettidba** [comment]
Closed with  fdf0708

**Comment by wesleyknutsmensura** [comment]
It seems that both msi installers still contain the previous version?

**Comment by spaghettidba** [comment]
You're absolutely right. Sorry, I updated with the correct files.
