### ISSUE TITLE
Replay doesn't work with Azure SQL

### ISSUE THREAD

**Issue by noamo48** [spaghettidba/WorkloadTools#60]
I tested SqlWorkload against a standard Azure SQL database today and found something weird. None of the commands replayed because it kept giving the error that "USE" statements are not allowed in Azure SQL. When I filtered through the events in the SQLite replay db, none of them actually contained a "USE" statement.

Is SqlWorkload inserting the "USE" statement? If so, it is a bug.

**Comment by spaghettidba** [comment]
I'll look into it, thanks

**Comment by spaghettidba** [comment]
Can't reproduce
