### ISSUE TITLE
Workloadconverter throws exception

### ISSUE THREAD

**Issue by JljHook** [spaghettidba/WorkloadTools#70]
I'm trying to convert trace file with RPC:completed events.

`C:\Program Files\WorkloadTools>Convertworkload.exe -i "C:\Traces\CustomTrace_2019-10-31.trc" -o C:\traces\CustomTrace_2019-10-31.sqlite -l c:\traces\convertworload.log
Info - ConvertWorkload.Program : ConvertWorkload, Version=1.3.4.0, Culture=neutral, PublicKeyToken=null 1.3.4
Info - WorkloadTools.Listener.Trace.TraceFileWrapper : SMO Version: Microsoft.SqlServer.ConnectionInfoExtended, Version=13.0.0.0, Culture=neutral, PublicKeyToken=89845dcd8080cc91
Error - ConvertWorkload.SqlTraceEventReader : Exception has been thrown by the target of an invocation.
Error - ConvertWorkload.SqlTraceEventReader : Failed to initialize object as reader.`

**Comment by spaghettidba** [comment]
Sorry, I know. Basically, Microsoft broke ConvertWorkload when they released SSMS 18.0 and its SMO. I am working on a solution, but for the time being there is no way to convert workloads.
