### ISSUE TITLE
Export WorkloadViewer as a "Report"

### ISSUE THREAD

**Issue by SQLGeordie** [spaghettidba/WorkloadTools#99]
I would like to be able to output the information seen in WorkloadViewer as some kind of report, this way it could be incorporated into a documentation for a migration project and/or be able to provide the information to the relevant people (ie. management) involved without having to have the tool themselves..

**Comment by spaghettidba** [comment]
There is PowerBI for that: open the "reports" folder under the workloadtools installation folder. Run the template and it will prompt for connection details. Fill in the info and proceed and it will load all the data in the pbix file, no need to have the database around :)
